[graph]
all-features = true

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
ignore = []

[licenses]
confidence-threshold = 0.92
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "Unicode-3.0",
  "Zlib"
]
exceptions = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
highlight = "all"
deny = []
skip = [
  { name = "getrandom", version = "=0.2.17" },
  { name = "getrandom", version = "=0.3.4" },
  { name = "hashbrown", version = "=0.14.5" },
  { name = "hashbrown", version = "=0.15.5" },
  { name = "linux-raw-sys", version = "=0.4.15" },
  { name = "r-efi", version = "=5.3.0" },
  { name = "rustix", version = "=0.38.44" },
  { name = "windows-sys", version = "=0.52.0" },
  { name = "windows-sys", version = "=0.59.0" },
  { name = "wit-bindgen", version = "=0.51.0" }
]
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
