{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chronos.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "chronos.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.clientPodSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: 50051
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.monitoringNamespaceSelector | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9898
{{- end }}
