{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.replicaCount) 0) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chronos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  minAvailable: {{ sub (int .Values.replicaCount) 1 }}
  selector:
    matchLabels:
      {{- include "chronos.selectorLabels" . | nindent 6 }}
{{- end }}
