apiVersion: v1
kind: Service
metadata:
  name: {{ include "chronos.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "chronos.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chronos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chronos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "chronos.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
